package com.Lisiniarivo.Application.Core;

public enum ErrorType {
	
	INTERNAL_ERROR,RESOURCE_ALREADY_EXISTS,RESOURCE_NOT_FOUND,INPUT_MISMATCH,
	NOT_AUTHORIZED,AUTHENTICATION_NEED,FILE_UPLOAD_ERROR;

}
